// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCsGOX-Ow8LFYxwJFov8BrUswq3H7hzto',
    appId: '1:613197314752:web:188a4598e16aff82bb8b25',
    messagingSenderId: '613197314752',
    projectId: 'flutter-auth-shopping',
    authDomain: 'flutter-auth-shopping.firebaseapp.com',
    storageBucket: 'flutter-auth-shopping.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhss25Rz6DXgasutu_WGrRJE6JlBobeHA',
    appId: '1:613197314752:android:dd6144d1d84640edbb8b25',
    messagingSenderId: '613197314752',
    projectId: 'flutter-auth-shopping',
    storageBucket: 'flutter-auth-shopping.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2-RMTA2CeRJTUPG0_hb-rPpE8WN9ZGR4',
    appId: '1:613197314752:ios:4614ff008d9fd264bb8b25',
    messagingSenderId: '613197314752',
    projectId: 'flutter-auth-shopping',
    storageBucket: 'flutter-auth-shopping.firebasestorage.app',
    iosBundleId: 'com.example.openFashion',
  );
}
